### ISSUE TITLE
Add virtual import for automatic console override

### ISSUE THREAD

**Issue by aleclarson** [patak-dev/vite-plugin-terminal#1]
```ts
import "virtual:terminal/register"
```

That import would hook into `console` calls, so that all browser logs appear in the terminal as well.

**Would you be willing to implement this?**
I don't have time right now, but maybe someone will be inspired by this idea and contribute :)

**Comment by patak-dev** [comment]
I think we may not need a different import. What about docummenting that you can push every `console.log` to the terminal using:
```js
import terminal from 'virtual:terminal'
globalThis.console = terminal
```
What I like about this, is that there may be cases were you want to dynamically change if you want logs in the terminal or the console.
I don't know if we win much by replacing that two lines with a single import, what do you think @aleclarson?

Note: we should make `'virtual:terminal'` export `console` in build mode, so the above code can be safely included in the bundle

**Comment by aleclarson** [comment]
The register module would preserve logs in the browser. Not sure how important that is though, so overwriting `globalThis.console` is probably good enough

**Comment by patak-dev** [comment]
See https://github.com/patak-dev/vite-plugin-terminal#redirect-console-logs-to-the-terminal
