### ISSUE TITLE
[ bug ] for build and browser

### ISSUE THREAD

**Issue by remigermain** [patak-dev/vite-plugin-terminal#14]
Hi, i have 2 errors , one in browser console,and second when i try to build

browser terminal: 
![image](https://user-images.githubusercontent.com/66946113/159027907-edd78aaa-ea33-48d6-bfec-3d2860a5239d.png)

and error for building
![image](https://user-images.githubusercontent.com/66946113/159028049-8b945e2f-19c6-401f-ac9e-feb01d5a7e1f.png)

vite config:
```js
envPrefix: "JOR_",
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./src"),
      },
    },
    root: "src/",
    plugins: [
      react(),
     Terminal({
        console: "terminal",
        output: ["terminal", "console"],
      })
    ],
  });
```
vite verison  v2.8.6
plugin version 1.0.1

**Comment by patak-dev** [comment]
Would you share a reproduction in GitHub or StackBlitz?

**Comment by patak-dev** [comment]
Closing as stale

**Comment by phproberto-bluebox** [comment]
I had this issue too. I found that `vite-plugin-terminal` was in `devDependencies` so not available on build. In this case you have to add a check to add the plugin only in dev mode:

```js
import Terminal from 'vite-plugin-terminal';

export default ({ mode }: { mode: string }) => {
  const isDev = mode === 'development';
  return defineConfig({
    plugins: [
      isDev && Terminal({
        console: "terminal",
        output: ["terminal", "console"],
      }),
    ],
  });
}
