### ISSUE TITLE
Vite 3 support

### ISSUE THREAD

**Issue by sean-hill** [patak-dev/vite-plugin-terminal#21]
Hey! I'm trying to install this plugin with a project using Vite 3. But I'm getting this error when trying to install:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: XXXXX@0.1.0
npm ERR! Found: vite@3.1.8
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.0.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0" from vite-plugin-terminal@1.0.2
npm ERR! node_modules/vite-plugin-terminal
npm ERR!   dev vite-plugin-terminal@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Looks like perhaps the peer dependency of vite needs to be updated?

**Comment by FossPrime** [comment]
Encountering a similar issue installing on Vite 3.2 with pnpm

```
 WARN  Issues with peer dependencies found
.
└─┬ vite-plugin-terminal 1.0.2
  ├── ✕ unmet peer vite@^2.0.0: found 3.2.2
  └─┬ @rollup/plugin-strip 2.1.0
    ├── ✕ missing peer rollup@"^1.20.0 || ^2.0.0"
    └─┬ @rollup/pluginutils 3.1.0
      └── ✕ missing peer rollup@^1.20.0||^2.0.0
Peer dependencies that should be installed:
  rollup@">=1.20.0 <2.0.0 || >=2.0.0 <3.0.0"

Done in 1.5s
```

**Comment by doppiscantsleep** [comment]
Same
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: msal-vue-sample@0.0.0
npm ERR! Found: vite@3.2.3
npm ERR! node_modules/vite
npm ERR!   dev vite@"^3.1.8" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"^2.0.0" from vite-plugin-terminal@1.0.2
npm ERR! node_modules/vite-plugin-terminal
npm ERR!   dev vite-plugin-terminal@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`
