### ISSUE TITLE
[ bug ] when the printed parameter has a percent sign , Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by n3taway** [patak-dev/vite-plugin-terminal#23]
```
[vite] Internal server error: URI malformed
```
version: 1.1.0

![image](https://github.com/patak-dev/vite-plugin-terminal/assets/15645831/3853ebe5-7d66-4773-9cac-3b4691c5344e)

![image](https://github.com/patak-dev/vite-plugin-terminal/assets/15645831/38e01dba-51bb-4f98-a1f6-4d8aec9c0f39)

It seems like the coding method can't handle percent signs
https://github.com/patak-dev/vite-plugin-terminal/blob/main/src/index.ts#L140C25-L140C25

**Comment by Andreoew** [comment]
I have this same problem, how to solve it?

**Comment by patak-dev** [comment]
Fixed by #25
