### ISSUE TITLE
[Feature] Add auto import like @vueuse/core or vue with vite-auto-import

### ISSUE THREAD

**Issue by harrytran998** [patak-dev/vite-plugin-terminal#4]
Thanks for the useful lib Patak <3. I installed this in my projects ✌🏻 .
Currently, if we want to log we must import this lib in the import.

```
import terminal from 'virtual:terminal';
terminal.log('Something Happening ::::');
```

So I think what if you combine this with the `vite-auto-import` + defined main debug method in like this in `vite.config.ts`

```
import ViteTerminal from 'vite-plugin-terminal';

ViteTerminal({
	classes: ['shopping', 'payment',...]
})
```

So we can use our code directly with that classes or not(default)

```
<script setup lang="ts">
terminal.shopping('This is shopping domain logs');
terminal.log('This is default logs');
terminal.payment('This is payment domain logs');
</script>
```

# Would you be willing to implement this?
I don't have time right now, but maybe someone will be inspired by this idea and contribute :)

**Comment by patak-dev** [comment]
There is an Auto Import example in the repo, here https://github.com/patak-dev/vite-plugin-terminal/tree/main/playground/autoimport
It uses unplugin-auto-import to make `terminal` global in your app.
Online Playground: https://stackblitz.com/fork/github-ejosid?file=main.ts&terminal=dev

Is this what you wanted?

**Comment by harrytran998** [comment]
Yes, it's exactly what I think about its 😆 - in minimal setup.
But greater when we have some config like 

```
import { defineConfig } from 'vite'
import autoImport from 'unplugin-auto-import/vite'
import terminal from 'vite-plugin-terminal'

export default defineConfig({
  plugins: [
    terminal({
    	custom: {
    		shopping: (...obj: any[]) => `Shopping: ${obj}`
    	}
    }),
    autoImport({
      imports: [
        {
          'virtual:terminal': ['terminal'],
        },
      ],
    }),
  ]
})
```

```js
terminal.shopping('Hello Patak Dev');
--> Output: 'Shopping: Hello Patak Dev'
```

**Comment by MarsOrBust24** [comment]
It would be great if this worked like typescript support in vite, where merely installing typescript auto configures typescript support.

with the incredible usefulness of forwarding `[Vite warn]` error messages to terminal, shimming `console` automatically when `'vite-plugin-terminal'` is present ought to be the default.

**Comment by patak-dev** [comment]
@harrytran998 about
```js
terminal.shopping('message')
```
I think this is out of the scope of the library. And you can use your own wrapper utils around console.log to achieve the same

@MarsOrBust24, at least for the moment, I prefer to keep it as opt-in. But the documentation could be updated to make this mode more prominent. PR welcome to move that section to the top, or add a big note pointing to the section. We can use (https://github.com/community/community/discussions/16925)

> **Note**
> This is a note
