### ISSUE TITLE
Terminal output out of order

### ISSUE THREAD

**Issue by vjee** [patak-dev/vite-plugin-terminal#7]
I have noticed that sometimes the order of the terminal output is not the same as the order of `terminal.<method>` calls.
Especially with larger messages (e.g. large tables) and when Vite is stopped (so it will start to ping) and then started again, causing the page to reload.
I can't reliably reproduce it though.

I guess it makes sense because you can't expect every http request to land in Vite sequentially.

Is this something you have noticed too, and would it be worth fixing?

We could put the `fetch` calls in a stack and resolve them sequentially.
Something like this:

```ts
type Task = () => Promise<any>

const stack: Task[] = []
let runner: Promise<void> | undefined

function pushTask(task: Task) {
  stack.push(task)
  if (!runner) runStack()
}

function runStack() {
  const task = stack.shift()
  runner = task ? runTask(task).finally(runStack) : undefined
}

function runTask(task: Task) {
  return new Promise<void>((resolve) => {
    const timeout = setTimeout(resolve, 1000)
    task().finally(() => {
      if (timeout) clearTimeout(timeout)
      resolve()
    })
  })
}
```

And then instead of doing `fetch(...)` we'd do `pushTask(() => fetch(...))`.
If a request takes more than 1 second, the next requests will start anyway so we wouldn't totally block all logs in case this happens.

**Comment by patak-dev** [comment]
Yes, we were discussing about it with @EstaniPP. I think he has a PR ready to send doing something similar to what you describe. @EstaniPP, could you tag @vjee once you push the PR so he can also check it?

**Comment by vjee** [comment]
Alright, will keep an eye open for that.

**Comment by patak-dev** [comment]
Merged https://github.com/patak-dev/vite-plugin-terminal/pull/6 👍🏼

**Comment by EstaniPP** [comment]
@vjee FYI PR fot this: https://github.com/patak-dev/vite-plugin-terminal/pull/9
