### ISSUE TITLE
Assert is backwards?

### ISSUE THREAD

**Issue by jods4** [patak-dev/vite-plugin-terminal#8]
For a method called `assert`, I'd have opposite expectations to what this cool lib is doing...

In other languages / framework I know of, an _assertion_ is expected to be true.
`assert` calls would throw or display a message when an assertion is violated, i.e. it's false.

[Example in C#](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debug.assert?view=net-6.0#system-diagnostics-debug-assert(system-boolean))
```csharp
// Checks that the index is positive.
// If it's not, display an error message.
Debug.Assert(index > -1);
```

This library displays a green message when asserts are true.
Seems to me it should instead display a _red_ message when asserts are _false_.

The choice of color (green) is itself an indication this is backwards: we need to know what's wrong (red) not what's working as intended (green).

**Comment by patak-dev** [comment]
Thanks @jods4! released with a proper assertion (and including the message "Assertion failed: " like the browser does) in 0.0.11

**Comment by jods4** [comment]
That was quick! Thanks 🙏
